### ISSUE TITLE
Cannot get /tags/

### ISSUE THREAD

**Issue by datvuthanh** [cwxyz007/hexo-theme-simple#5]
Thank u for great theme! But i can't go to tags page.

**Comment by 0x-jerry** [comment]
You're welcome!

I got your email, and yes! I will develop the category page in this weekend!

**Comment by 0x-jerry** [comment]
For this issue, please provide `package.json` and `build log` to help locate the bug

**Comment by 0x-jerry** [comment]
I will close this issue, and if you have any problem, feel free to open a new issue.
